# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
baseurl:          /Flurl    

author:
  name:           Todd Menier
  url:            https://twitter.com/tmenier

paginate:         1

github:
  repo:           https://github.com/tmenier/flurl
