version: 1.0.0-{branch}-{build}

image: Visual Studio 2017  

init:
  - dotnet --version

pull_requests:
  do_not_increment_build_number: true

build_script:
  - cmd: dotnet build -c Release src\Flurl
  - cmd: dotnet build -c Release src\Flurl.Http
  - cmd: dotnet build -c Release test\Flurl.Test

artifacts:
  - path: '**\*.nupkg'
