version: 1.0.0-{branch}-{build}

image: Visual Studio 2017

configuration: Release

build_script:
  - cmd: msbuild /t:restore Flurl.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" && msbuild /t:pack Flurl.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

test_script:
  - cmd: call cmd /C "cd .\build & test.cmd"

artifacts:
  - path: '**\*.nupkg'