version: 1.0.0-{branch}-{build}

image: Visual Studio 2019

init:
  - dotnet --version

pull_requests:
  do_not_increment_build_number: true

build_script:
  - cmd: call cmd /C "cd .\build & build.cmd"

test_script:
  - cmd: call cmd /C "cd .\build & test.cmd"

artifacts:
  - path: '**\*.*nupkg'