version: 1.0.0-{branch}-{build}

pull_requests:
  do_not_increment_build_number: true

os: Visual Studio 2015

install:
  - ps: .\build\scripts\install.ps1

build_script:
  - ps: .\build\scripts\show-dotnet-info.ps1
  - cmd: call cmd /k "cd .\build & pack.flurl.cmd & pack.flurl.http.cmd"  

test_script:
  - cmd: call cmd /k "cd .\build & test.cmd"

artifacts:
  - path: '**\*.nupkg'